on: [push]

name: Cross Compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Strip arm
        if: ${{ matrix.target }} = "armv7-unknown-linux-musleabihf"
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: run
          args: /usr/local/arm-linux-musleabihf/bin/strip -s target/${{ matrix.target }}/release/outdoor -o target/${{ matrix.target }}/release/outdoor.stripped

      - name: Strip x86
        if: ${{ matrix.target }} = "x86_64-unknown-linux-musl"
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: run
          args: /usr/bin/strip -s target/${{ matrix.target }}/release/outdoor -o target/${{ matrix.target }}/release/outdoor.stripped

