on: [push]

name: Cross Compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Archive binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: outdoor-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/outdoor
